### ISSUE TITLE
Checkpoint 1 Ready for review

### ISSUE THREAD

**Issue by johnoliver42** [johnoliver42/InvoiceMaker#1]
@pawaitemadisoncollege - checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
Hi @johnoliver42!

**Problem statement** Clearly describes the problem and the proposed solution.

**User stories** Do a good job describing what the application will do from a user perspective. The MVP stories should meet the Ent Java project requirements, such as full crud, auth.  

- [ ] I did not see a story for signing into the application. While is may be assumed, I think it is more thorough to explicitly include it since your stories do seem to differentiate between user and registered user. 

**Screens and Site Map** The site map does a good job clearly showing flow and addresses each user story. A screen with relevant fields seems to exist for each story.

- [ ] I noticed a delete account button but did not see a story for this. These should match up, so either remove the delete button or add a story (likely not mvp?). Same comment for edit account.

**Project plan** Does a good job through week 6 detailing out tasks, by listing the jsps you will be working on. 

- [ ] Planning would benefit from continuing to detail out the creation of the resources needed for each user story, servlets/controllers, entity per table, unit tests, for example.
- [ ] I noticed reference to a role table but I didn't see a story associated with any roles, so I am not sure this is needed. 

**Time Log** Describes what was done, when and how long it took. Good!
